Modified exec_command to understand multi option command put "ssl" next last command.
cmer/lg-tv-control-macos pull request #8
Opened 2023-04-29 08:24 UTC by fakeskimo

"ssl" is need to put just next of second command part when using current version lgtv [commit link](https://github.com/klattimer/LGWebOSRemote/commit/514be54225986aa2c14f6fd12ddef7bbc4378cc1) 

Example:
lgtv MyTV startApp com.webos.app.hdmi1 ssl --> fails
lgtv MyTV startApp ssl com.webos.app.hdmi1 --> success

Therefore I added step to put "ssl" next of second command part in exec_command.

2023-04-29 15:16 UTC, cmer requested changes
This is awesome thank you. Could you put back the `lgtv_disabled` function before I approve, however?

2023-04-30 12:16 UTC, fakeskimo commented
I put back original "lgtv_disabled" function to resolve the conflict. LMK if there is any further issue. Thanks!

2023-05-01 05:11 UTC, zakkhoyt commented
@fakeskimo YES! Great catch. I have been trying to diagnose this problem today. It hadn't occurred that the args were out of order.

2023-05-01 05:16 UTC, zakkhoyt commented on lgtv_init.lua
> +    if space_loc then
```suggestion

    --- "ssl" must be the first argument for a command. Advance it to the expected position.
    if space_loc then
```

2023-05-01 12:24 UTC, cmer approved these changes

2023-05-01 12:25 UTC, merged